# Docker Compose for Development
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: ai-pipeline-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ai-pipeline
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis for caching and job queues
  redis:
    image: redis:7-alpine
    container_name: ai-pipeline-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:

networks:
  default:
    name: ai-pipeline-dev