apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: ai-pipeline
  labels:
    app: config-service
spec:
  selector:
    app: config-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP