apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: ai-pipeline
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
  - name: vault
    port: 8200
    targetPort: 8200
    protocol: TCP
  type: ClusterIP